# 数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://150.158.214.106:3306/db_club?serverTimezone=UTC&useSSL=false
    name: defaultDataSource
    username: root
    password: wyr0307
  # redis配置
  redis:
    host: 150.158.214.106
    port: 6379
    password: wyr0307
# Mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sgqn.club.base.entity,com.sgqn.club.base.dto

# json统一格式
token:
  security-key: security-key-value
  expires-time: 8640000